### ISSUE TITLE
Pin different text at 13:36

### ISSUE THREAD

**Issue by meisterrados** [yeldiRium/telegram-bots#37]
Make the bot send different messages at 13:36 that are pinned.
The bot always sends "doooods" currently.
Make him choose from a set of messages, just like the insults in case of a mistimed "1337" post.

**Comment by yeldiRium** [comment]
Contributions welcome.

The translation for the pin text has to be replaced with an array of strings and the usage of it (should only be one place) must replaced with the random selection logic already in use in the 1337 command.

This should be a good issue for beginners trying to learn the codebase.

**Comment by yeldiRium** [comment]
Someone suggested `It's dudes, my wednesday`
