### ISSUE TITLE
add contributors to package.json

### ISSUE THREAD

**Issue by yeldiRium** [yeldiRium/telegram-bots#38]
We have several contributors already and should add them to the package.json.
So far we need to add:

- @meisterrados 
- @Fritz-theCat 
- @xuiqzy 
- @dotKuro
- @eduardklusch

To the mentioned people: May I add you with your full names and e-mails? Does anyone not want to be mentioned in the code?

**Comment by eduardklusch** [comment]
ACK.

**Comment by yeldiRium** [comment]
I forgot to mention @strangedev!

**Comment by meisterrados** [comment]
Yes, that's fine with me :)

**Comment by Fritz-theCat** [comment]
Thats okay

**Comment by dotKuro** [comment]
Yeah, add me with full name and email :)

**Comment by yeldiRium** [comment]
Got verbal agreement from @strangedev.

**Comment by xuiqzy** [comment]
fine with me, too :D
